name: kitsune
version: '1.0.0'
main: shx.kitsune.Kitsune
author: Shiro Interactive
website: https://shiro.eu.org
description: Kitsune Core
api-version: '1.20'
softdepend:
  - vault
commands:
  kitsune:
    description: Kitsune commands
    permission: shx.kitsune
    aliases:
      - kitsune
    usage: kitsune
    permission-message: You don't have permission to use this command